version: '3'
services:
    rust:
        build:
            context: .
            dockerfile: ./docker/rust/Dockerfile
        environment:
            USER: root
            command: cargo watch -x "run" -w src
        volumes:
            - .:/app:cached
        stdin_open: true
        tty: true

    node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        container_name: node
        volumes:
            - .:/app
        tty: true
        ports:
            - 3000:3000

    web:
        build:
            context: .
            dockerfile: ./docker/centos/Dockerfile
        container_name: "centos"
        ports:
            - 80:80
        volumes:
            - "./html:/var/www/html"
        privileged: true